version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/istio"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/jaegertracing"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/kiali"
    schedule:
      interval: "daily"
