kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: istio-operator
          image: "{{ .Values.image.hub }}/operator:{{ .Values.image.tag }}"
          command:
            - operator
            - server
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Values.watchNamespace }}
            - name: LEADER_ELECTION_NAMESPACE
              value: {{ .Release.Name }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ .Release.Name }}
            - name: WAIT_FOR_RESOURCES_TIMEOUT
              value: 300s
            - name: REVISION
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          imagePullPolicy: {{ .Values.image.pullPolicy }}