name: base

on:
  push:
    paths:
      - '.github/workflows/base.yml'
      - 'base/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: v0.4.2
      - run: |
          cat > ~/.docker/config.json << EOF
          ${{ secrets.DOCKER_CONFIG }}
          EOF
      - run: cd base && make build