name: build-env

on:
  push:
    paths:
      - '.github/workflows/build-env.yml'
      - 'build-env/**'

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: v0.4.1
      - run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: VERSION=${{ github.sha }} docker buildx bake --set=*.context=./build-env -f ./build-env/bake.hcl arm64 --push