name: istio-proxyv2
"on":
  push:
    paths:
    - .github/workflows/istio-proxyv2.yml
    - build/istio/Dockerfile.proxyv2
    - build/istio/Dockerfile.version
    - build/istio/Makefile
jobs:
  proxyv2:
    runs-on:
    - ubuntu-latest
    defaults:
      run:
        working-directory: build/istio
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        path: /tmp/.buildx-cache
        restore-keys: ${{ runner.os }}-buildx-
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Versioned Build
      if: github.ref == 'refs/heads/master'
      run: make build HUB=querycapistio NAME=proxyv2
    - name: Temp Build
      if: github.ref != 'refs/heads/master'
      run: make build TAG=temp-${{ github.sha }} HUB=querycapistio NAME=proxyv2
  sync-proxyv2:
    runs-on:
    - self-hosted
    - arm64
    needs:
    - proxyv2
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: build/istio
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_MIRROR_PASSWORD }}
        registry: ${{ secrets.DOCKER_MIRROR_REGISTRY }}
        username: ${{ secrets.DOCKER_MIRROR_USERNAME }}
    - run: |-
        export TAG=$(make image HUB=querycapistio NAME=proxyv2)

        docker buildx build --push --platform linux/arm64,linux/amd64 --tag ${{ secrets.DOCKER_MIRROR_REGISTRY }}/${TAG} --build-arg TAG=${TAG} --file ../Dockerfile.sync .
