name: istios
"on":
  push:
    paths:
    - docker/istios/*
jobs:
  base:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: docker login
      run: |
        cat > ~/.docker/config.json << EOF
        ${{ secrets.DOCKER_CONFIG }}
        EOF
    - run: cd docker/istios && NAME=base make build
  operator:
    runs-on:
    - ubuntu-latest
    needs:
    - base
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: docker login
      run: |
        cat > ~/.docker/config.json << EOF
        ${{ secrets.DOCKER_CONFIG }}
        EOF
    - run: cd docker/istios && NAME=operator make build
  pilot:
    runs-on:
    - ubuntu-latest
    needs:
    - base
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: docker login
      run: |
        cat > ~/.docker/config.json << EOF
        ${{ secrets.DOCKER_CONFIG }}
        EOF
    - run: cd docker/istios && NAME=pilot make build
  proxyv2:
    runs-on:
    - ubuntu-latest
    needs:
    - base
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: docker login
      run: |
        cat > ~/.docker/config.json << EOF
        ${{ secrets.DOCKER_CONFIG }}
        EOF
    - run: cd docker/istios && NAME=proxyv2 make build
