name: istio

"on":
  push:
    paths:
      - .github/workflows/istio.yml

jobs:
  envoy-arm64:
    runs-on: [ "self-hosted", "linux", "ARM64" ]

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        name: Login docker.io
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}

      - run: make build.envoy

      - uses: actions/upload-artifact@v2
        with:
          name: envoy-linux-arm64
          path: .tmp/envoy-linux-arm64

  istio:
    needs:
      - envoy-arm64

    runs-on: [ "self-hosted", "linux", "ARM64" ]

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        name: Login docker.io
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}

      - uses: actions/download-artifact@v2
        with:
          name: envoy-linux-arm64
          path: .tmp/envoy-linux-arm64

      #      - uses: dawidd6/action-download-artifact@v2
      #        with:
      #          workflow: envoy
      #          run_id: 1030924878
      #          name: envoy-linux-arm64
      #          path: .tmp/envoy-linux-arm64

      - name: Build Istio Images
        run: |
          export HOME=$(echo ~);
          make dockerx.istio;
