name: istio-proxyv2

on:
  push:
    paths:
      - '.github/workflows/istio-proxyv2.yml'
      - 'istios/**'
      - '_sync/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@master
      - uses: docker/setup-buildx-action@master
      - name: docker login
        run: |
          cat > ~/.docker/config.json << EOF
          ${{ secrets.DOCKER_CONFIG }}
          EOF
      - run: cd istios && make build.proxyv2
      - run: cd istios && make sync.proxyv2