name: istio-envoy

on:
  push:
    paths:
      - '.github/workflows/istio-envoy.yml'
      - 'istio-envoy/**'

jobs:
  build-arm64:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v1
      - run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: VERSION=$(cat ./istio-envoy/.version) docker buildx bake --set=*.context=./istio-envoy -f ./istio-envoy/bake.hcl arm64 --push