name: jaegertracing-all-in-one
"on":
  push:
    paths:
    - build/jaegertracing/Dockerfile.all-in-one
    - build/jaegertracing/Dockerfile.version
jobs:
  all-in-one:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Versioned Build
      if: github.ref == 'refs/heads/master'
      run: cd build/jaegertracing && make build HUB=querycapistio NAME=all-in-one
    - name: Temp Build
      if: github.ref != 'refs/heads/master'
      run: cd build/jaegertracing && make build HUB=querycapistio NAME=all-in-one TAG=temp-${{ github.sha }}
