name: jaegertracing

on:
  push:
    paths:
      - '.github/workflows/jaegertracing.yml'
      - 'jaegertracing/**'
      - '_sync/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@master
      - uses: docker/setup-buildx-action@master
      - name: docker login
        run: |
          cat > ~/.docker/config.json << EOF
          ${{ secrets.DOCKER_CONFIG }}
          EOF
      - uses: actions/setup-node@v1
      - run: cd jaegertracing && make build
      - run: cd jaegertracing && make sync