name: sync-proxyv2
"on":
  push:
    paths:
    - sync/Dockerfile.proxyv2
jobs:
  sync:
    runs-on:
    - self-hosted
    - linux
    - ARM64
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: docker login
      run: |
        cat > ~/.docker/config.json << EOF
        ${{ secrets.DOCKER_CONFIG }}
        EOF
    - run: cd sync && NAME=proxyv2 make sync
